import pandas as pd
import matplotlib.pyplot as plt

# --- Configuration ---
# Set the path to the CSV file generated by your training script
CSV_FILE_PATH = './trained_models/Bpp-v0/training-at-grace-robot/training_log.csv'

# Set a smoothing factor (0 = no smoothing, 0.9 = high smoothing)
SMOOTHING_WEIGHT = 0.6

def plot_from_csv(file_path, smoothing_weight=0.0):
    """Loads data from a CSV and generates training plots."""
    try:
        # Load the data using pandas
        df = pd.read_csv(file_path)
        print(f"Successfully loaded {len(df)} records from {file_path}")
    except FileNotFoundError:
        print(f"Error: The file was not found at {file_path}")
        return

    # Apply exponential moving average for smoothing
    if smoothing_weight > 0:
        for col in df.columns:
            if col not in ['update_step', 'total_timesteps']:
                df[col] = df[col].ewm(alpha=(1 - smoothing_weight)).mean()

    # --- Plot 1: Performance Metrics ---
    plt.figure(figsize=(12, 7))
    plt.plot(df['update_step'], df['mean_space_ratio'], label='Mean Space Ratio')
    plt.plot(df['update_step'], df['mean_reward'], label='Mean Reward', alpha=0.8)
    plt.plot(df['update_step'], df['mean_items_packed'], label='Mean Items Packed', linestyle='--')
    
    plt.title('Performance Metrics during Training')
    plt.xlabel('Training Updates')
    plt.ylabel('Value')
    plt.grid(True, which='both', linestyle='--', linewidth=0.5)
    plt.legend()
    plt.tight_layout()
    plt.savefig('performance_plot.png')
    plt.show()

    # --- Plot 2: Loss Functions ---
    plt.figure(figsize=(12, 7))
    plt.plot(df['update_step'], df['value_loss'], label='Value Loss')
    plt.plot(df['update_step'], df['action_loss'], label='Action Loss')
    plt.plot(df['update_step'], df['entropy_loss'], label='Entropy Loss')

    plt.title('Loss Functions during Training')
    plt.xlabel('Training Updates')
    plt.ylabel('Loss Value')
    plt.grid(True, which='both', linestyle='--', linewidth=0.5)
    plt.legend()
    plt.tight_layout()
    plt.savefig('losses_plot.png')
    plt.show()


if __name__ == '__main__':
    plot_from_csv(CSV_FILE_PATH, smoothing_weight=SMOOTHING_WEIGHT)